#!/bin/sh

	# default
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

	# display
xset s off
xrandr --dpi 102

	# keyboard
xset r rate 250 30

xbindkeys

	# dbus, TODO: both lines do the same! only last one works!
#source /etc/X11/xinit/xinitrc.d/30-dbus
#eval $(/usr/bin/dbus-launch --sh-syntax --exit-with-session)

	# gtk
export GTK_OVERLAY_SCROLLING=0

	# gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GPG_AGENT_INFO SSH_AUTH_SOCK

	# awesome
exec awesome

