#!/bin/sh

	# global xinit scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

	# dpi
xrandr --dpi 84
	
	# keyboard
xset r rate 250 30
setxkbmap de nodeadkeys

	# awesome wm
exec awesome
